"""Add MasterProduct and CodeRegistry models

Revision ID: 5cdeadb27e7f
Revises: 001_add_users
Create Date: 2025-12-28 00:07:19.242381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdeadb27e7f'
down_revision: Union[str, Sequence[str], None] = '001_add_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clean_code', sa.String(length=100), nullable=False),
    sa.Column('canonical_description', sa.String(length=500), nullable=True),
    sa.Column('canonical_brand', sa.String(length=200), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('alternate_codes', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_code_registry_brand', 'code_registry', ['canonical_brand'], unique=False)
    op.create_index('idx_code_registry_code', 'code_registry', ['clean_code'], unique=False)
    op.create_index(op.f('ix_code_registry_clean_code'), 'code_registry', ['clean_code'], unique=True)
    op.create_table('master_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_number', sa.Integer(), nullable=False),
    sa.Column('clean_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source_list_id', sa.Integer(), nullable=False),
    sa.Column('original_list_name', sa.String(length=255), nullable=False),
    sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_list_id'], ['catalogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_master_products_brand', 'master_products', ['brand'], unique=False)
    op.create_index('idx_master_products_code', 'master_products', ['clean_code'], unique=False)
    op.create_index('idx_master_products_index', 'master_products', ['index_number'], unique=False)
    op.create_index('idx_master_products_review', 'master_products', ['review_status'], unique=False)
    op.create_index('idx_master_products_source', 'master_products', ['source_list_id'], unique=False)
    op.create_index(op.f('ix_master_products_brand'), 'master_products', ['brand'], unique=False)
    op.create_index(op.f('ix_master_products_clean_code'), 'master_products', ['clean_code'], unique=False)
    op.create_index(op.f('ix_master_products_index_number'), 'master_products', ['index_number'], unique=False)
    op.create_index(op.f('ix_master_products_review_status'), 'master_products', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_products_review_status'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_index_number'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_clean_code'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_brand'), table_name='master_products')
    op.drop_index('idx_master_products_source', table_name='master_products')
    op.drop_index('idx_master_products_review', table_name='master_products')
    op.drop_index('idx_master_products_index', table_name='master_products')
    op.drop_index('idx_master_products_code', table_name='master_products')
    op.drop_index('idx_master_products_brand', table_name='master_products')
    op.drop_table('master_products')
    op.drop_index(op.f('ix_code_registry_clean_code'), table_name='code_registry')
    op.drop_index('idx_code_registry_code', table_name='code_registry')
    op.drop_index('idx_code_registry_brand', table_name='code_registry')
    op.drop_table('code_registry')
    # ### end Alembic commands ###
